### ISSUE TITLE
How to align icon to the middle of the button?

### ISSUE THREAD

**Issue by burakkilic** [kubatruhlar/JTImageButton#2]
Hello;

I couldn't align the icon to the center of the button.  Here is the code:

     [_addButton createTitle:@"EKLE"
                  withIcon:myImage
                      font:[UIFont fontWithName:@"OpenSans" size:22.0]
                iconHeight:JTImageButtonIconHeightDefault
               iconOffsetY:JTImageButtonIconOffsetYNone];
    _addButton.titleColor = [UIColor whiteColor];
    _addButton.borderColor = [Helper color:@"#9c006c"];
    _addButton.bgColor = [Helper color:@"#9c006c"];
    _addButton.highlightAlpha = 0.6;
    _addButton.touchEffectEnabled = YES;
    _addButton.cornerRadius = 3.0;
    _addButton.iconColor = [UIColor whiteColor];

And result is:

![screen shot 2016-11-17 at 12 34 59](https://cloud.githubusercontent.com/assets/123382/20383839/00d47cc8-acba-11e6-940a-dae82e059f86.png)

Where am I wrong?

**Comment by kubatruhlar** [comment]
Hi, use `iconOffsetY` parameter.
