### ISSUE TITLE
how to vertically aligned image + title?

### ISSUE THREAD

**Issue by hemang-ega** [kubatruhlar/JTImageButton#3]
**how to vertically aligned image + title?**

**Comment by kubatruhlar** [comment]
Hi, use `iconOffsetY` parameter for icon and `contentVerticalAlignment`, `titleEdgeInsets` and `baselineAdjustment` properties for content itself.

**Comment by hemang-ega** [comment]
Ok, thanks! It seems that there's no easiest (direct) way available for this stuff. You should consider adding this soon. It's highly in demand.
