### ISSUE TITLE
Why does setting border size to 0 still create a border?

### ISSUE THREAD

**Issue by Sweeper777** [kubatruhlar/JTImageButton#7]
I used the following code:

        jtButton.borderWidth = 0
        jtButton.bgColor = UIColor(hex: "5abb5a")
        jtButton.titleColor = .white
        jtButton.iconColor = .white
        jtButton.createTitle("Home", withIcon: #imageLiteral(resourceName: "home"), font: nil, iconOffsetY: 0)
        jtButton.touchEffectEnabled = true
        jtButton.cornerRadius = jtButton.height / 2

I have already set the border width to 0 in the first line, but it appears to still have a border:

<img width="632" alt="2017-09-16 8 56 24" src="https://user-images.githubusercontent.com/13585047/30519138-772fd37a-9b86-11e7-9dd9-1f7a1c29d2ac.png">

You can see on the border there there is a slightly brighter green color.

**Comment by kubatruhlar** [comment]
Try to set `borderWidth` after the `createTitle`. This could be improved, indeed

**Comment by Sweeper777** [comment]
Can you make it so that I does not have to set it after `createTitle`? A method should have as few side effects as possible, should it not?
